### ISSUE TITLE
PatternSyntaxException when processing certain JARs

### ISSUE THREAD

**Issue by tdegueul** [alien-tools/maracas#19]
`SpoonHelpers::matchingSignatures` throws an exception on some JARs here:

https://github.com/alien-tools/maracas/blob/ddd71ce9a07ef3d8e695b071cf0c5a4eb4339922/core/src/main/java/com/github/maracas/util/SpoonHelpers.java#L74

```
java.util.regex.PatternSyntaxException: Unclosed group near index 95
\(com.google.common.collect.RegularImmutableBiMap(com.google.common.collect.ImmutableMapEntry,?
	at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
	at java.base/java.util.regex.Pattern.accept(Pattern.java:1878)
	at java.base/java.util.regex.Pattern.group0(Pattern.java:3053)
	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2124)
	at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1783)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
	at java.base/java.lang.String.replaceAll(String.java:2939)
	at com.github.maracas.util.SpoonHelpers.matchingSignatures(SpoonHelpers.java:76)
	at com.github.maracas.delta.Delta$1.lambda$visit$6(Delta.java:171)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at com.github.maracas.delta.Delta$1.visit(Delta.java:172)
	at com.github.maracas.delta.JApiCmpDeltaVisitor$1.visit(JApiCmpDeltaVisitor.java:46)
	at japicmp.output.Filter.filter(Filter.java:47)
	at com.github.maracas.delta.JApiCmpDeltaVisitor.visit(JApiCmpDeltaVisitor.java:33)
	at com.github.maracas.delta.Delta.fromJApiCmpDelta(Delta.java:86)
```

See for instance the failing test https://github.com/alien-tools/maracas/blob/ddd71ce9a07ef3d8e695b071cf0c5a4eb4339922/core/src/test/java/com/github/maracas/PopularLibrariesTest.java#L28-L35

It would also be amazing if we could avoid Regex altogether ;)

**Comment by tdegueul** [comment]
Fixed in 221c08861245579ec0bfb2cba7f7e2f6e51c3f19, though it would still be better to avoid regex altogether later ;)
